# Generated by Django 4.0.4 on 2022-04-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.CharField(default='fizyka', max_length=100),
            preserve_default=False,
        ),
    ]
