# Generated by Django 4.0.4 on 2022-04-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='Wrocław', max_length=100),
            preserve_default=False,
        ),
    ]
